name: "[CI] Lint"

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUBY_VERSION: 2.7.6
  NODE_VERSION: 16.9.1

jobs:
  lint-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm ci
        name: Install JS deps

      - name: Lint and Rubocop
        run: |
          bundle exec rubocop -P
          bundle exec erblint app/**/*.erb

      - run: npm run lint
        name: Lint JS files
